# A reference to your project's ID.
# It can be found on your project's dashboard.
project_id = "avbwpuxhkyvfyonrpbqg"

[api]
# Port to use for the API URL.
port = 54321

# Schemas to expose on your API. Defaults to "public". Some schemas have implicit
# behaviours and shouldn't be exposed (e.g., *graphql*, *auth*, *storage*,
# *extensions*, *realtime*). Only expose these when you know what you're doing.
schemas = ["public"]

# Extra schemas to add to the search_path of every request.
extra_search_path = ["public", "extensions"]

# The maximum number of rows returns from a view, table, or function.
# Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322

# Major PostgreSQL version to use.
# Supported versions: 15, 14, 13.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

[inbucket]
# Port to use for the email testing server.
port = 54324

# Port to use for the email testing SMTP server.
smtp_port = 54325

[storage]
# The maximum file size allowed for uploads.
# File size is in bytes. Default is 5MB.
file_size_limit = 52428800

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"

# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]

# How long tokens are valid for (in seconds). Default is 3600 (1 hour), maximum 604,800 seconds (one week).
jwt_expiry = 3600

# If disabled, users will be unable to sign up without an invitation.
enable_signup = true

[auth.email]
# Enable or disable email auth
enable_signup = true
enable_confirmations = false

# Use a custom SMTP server instead of the built-in email provider.
# [auth.email.smtp]
# host = ""
# port = 587
# user = ""
# pass = ""
# admin_email = ""

# This function is called whenever a new user signs up.
# [auth.email_hook.invite]
# enabled = true
# uri = "https://example.com/v1/invite"

# This function is called whenever a user attempts to sign up.
# [auth.email_hook.signup]
# enabled = true
# uri = "https://example.com/v1/signup"

# This function is called whenever a user attempts to reset their password.
# [auth.email_hook.recovery]
# enabled = true
# uri = "https://example.com/v1/recovery"

# This function is called whenever a user changes their email address.
# [auth.email_hook.email_change]
# enabled = true
# uri = "https://example.com/v1/email_change"

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.email_hook.magic_link]
# enabled = true
# uri = "https://example.com/v1/magic_link"

# This function is called whenever a user is deleted.
# [auth.email_hook.user_deletion]
# enabled = true
# uri = "https://example.com/v1/user_deletion"

# Use a custom access token generation function.
# [auth.custom_access_token]
# enabled = true
# uri = "https://example.com/v1/custom_access_token"

# Use a custom refresh token generation function.
# [auth.custom_refresh_token]
# enabled = true
# uri = "https://example.com/v1/custom_refresh_token"

# Use a custom logout function.
# [auth.custom_logout]
# enabled = true
# uri = "https://example.com/v1/custom_logout"

# Use a custom password verification function.
# [auth.custom_password_verification]
# enabled = true
# uri = "https://example.com/v1/custom_password_verification"

# Use a custom session management function.
# [auth.custom_session_management]
# enabled = true
# uri = "https://example.com/v1/custom_session_management"

# Use a custom MFA verification function.
# [auth.custom_mfa_verification]
# enabled = true
# uri = "https://example.com/v1/custom_mfa_verification"

# Use a custom MFA enrollment function.
# [auth.custom_mfa_enrollment]
# enabled = true
# uri = "https://example.com/v1/custom_mfa_enrollment"

# Use a custom SAML provider.
# [auth.custom_saml]
# enabled = true
# uri = "https://example.com/v1/custom_saml"

# Use a custom OIDC provider.
# [auth.custom_oidc]
# enabled = true
# uri = "https://example.com/v1/custom_oidc"

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.apple]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.azure]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.bitbucket]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.discord]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.facebook]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.github]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.gitlab]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.google]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.keycloak]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.linkedin]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.notion]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.spotify]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.twitch]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.twitter]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.workos]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oauth.zoom]
# enabled = false
# client_id = ""
# secret = ""
# redirect_uri = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.saml.azure]
# enabled = false
# metadata_url = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.saml.okta]
# enabled = false
# metadata_url = ""

# This function is called whenever a user attempts to log in with a third party provider.
# [auth.external.oidc.keycloak]
# enabled = false
# client_id = ""
# secret = ""
# issuer_url = ""

[edge_runtime]